import type { Metadata } from "next";
import "./globals.css";
import HomeProvider from "./provider";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "pf-movie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning data-mode="dark" style={{ colorScheme: "dark" }}>
      <body suppressHydrationWarning>
        <HomeProvider>
          <Navbar />
          <main>{children}</main>
        </HomeProvider>
      </body>
    </html>
  );
}
