import type { Metadata } from "next";
import "./globals.css";
import HomeProvider from "./provider";
import Navbar from "@/components/ui/navbar";
import { ColorModeScript } from "@yamada-ui/react";

export const metadata: Metadata = {
  title: "pf-movie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ja"
      suppressHydrationWarning
    >
      <body suppressHydrationWarning>
        <ColorModeScript initialColorMode={"dark"} />
        <HomeProvider>
          <Navbar />
          <main>{children}</main>
        </HomeProvider>
      </body>
    </html>
  );
}
