import type { Metadata } from "next";
import "./globals.css";
import { ColorModeScript, UIProvider } from "@yamada-ui/react";
import { config, theme } from "@/themes";

export const metadata: Metadata = {
  title: "pf-movie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ColorModeScript />

        <UIProvider theme={theme} config={config}>{children}</UIProvider>
      </body>
    </html>
  );
}
